[build]
  base = "web-admin"
  command = "npm ci && npm run build"
  publish = "web-admin/dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

